/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-13-2007
 * 
 * XDoclet definition:
 * @struts.form name="forumeditForm"
 */
public class ForumeditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String id;

	/** manager property */
	private String manager;

	/** forumname property */
	private String forumname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the manager.
	 * @return String
	 */
	public String getManager() {
		return manager;
	}

	/** 
	 * Set the manager.
	 * @param manager The manager to set
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/** 
	 * Returns the forumname.
	 * @return String
	 */
	public String getForumname() {
		return forumname;
	}

	/** 
	 * Set the forumname.
	 * @param forumname The forumname to set
	 */
	public void setForumname(String forumname) {
		this.forumname = forumname;
	}
}