/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-06-2007
 * 
 * XDoclet definition:
 * @struts.form name="ForumForm"
 */
public class ForumForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** forumid property */
	private String forumid;                     //论坛id

	/** forumname property */
	private String forumname;					//论坛名称

	/*
	 * Generated Methods
	 */
	private int pageid=0;
	private String name;
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPageid() {
		return pageid;
	}

	public void setPageid(int pageid) {
		this.pageid = pageid;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the forumid.
	 * @return String
	 */
	public String getForumid() {
		return forumid;
	}

	/** 
	 * Set the forumid.
	 * @param forumid The forumid to set
	 */
	public void setForumid(String forumid) {
		this.forumid = forumid;
	}

	/** 
	 * Returns the forumname.
	 * @return String
	 */
	public String getForumname() {
		return forumname;
	}

	/** 
	 * Set the forumname.
	 * @param forumname The forumname to set
	 */
	public void setForumname(String forumname) {
		this.forumname = forumname;
	}
}