/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-05-2007
 * 
 * XDoclet definition:
 * @struts.form name="registerForm"
 */
public class RegisterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** mail property */
	private String mail;

	/** tx property */
	private String tx;

	/** signature property */
	private String signature;

	/** sex property */
	private String sex;

	/** password1 property */
	private String password1;

	/** username property */
	private String username;

	/** lxdz property */
	private String lxdz;

	/** tel property */
	private String tel;

	/** grzy property */
	private String grzy;

	/** realname property */
	private String realname;

	/** qq property */
	private String qq;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the mail.
	 * @return String
	 */
	public String getMail() {
		return mail;
	}

	/** 
	 * Set the mail.
	 * @param mail The mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/** 
	 * Returns the tx.
	 * @return String
	 */
	public String getTx() {
		return tx;
	}

	/** 
	 * Set the tx.
	 * @param tx The tx to set
	 */
	public void setTx(String tx) {
		this.tx = tx;
	}




	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the password1.
	 * @return String
	 */
	public String getPassword1() {
		return password1;
	}

	/** 
	 * Set the password1.
	 * @param password1 The password1 to set
	 */
	public void setPassword1(String password1) {
		this.password1 = password1;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the lxdz.
	 * @return String
	 */
	public String getLxdz() {
		return lxdz;
	}

	/** 
	 * Set the lxdz.
	 * @param lxdz The lxdz to set
	 */
	public void setLxdz(String lxdz) {
		this.lxdz = lxdz;
	}

	/** 
	 * Returns the tel.
	 * @return String
	 */
	public String getTel() {
		return tel;
	}

	/** 
	 * Set the tel.
	 * @param tel The tel to set
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/** 
	 * Returns the grzy.
	 * @return String
	 */
	public String getGrzy() {
		return grzy;
	}

	/** 
	 * Set the grzy.
	 * @param grzy The grzy to set
	 */
	public void setGrzy(String grzy) {
		this.grzy = grzy;
	}

	/** 
	 * Returns the realname.
	 * @return String
	 */
	public String getRealname() {
		return realname;
	}

	/** 
	 * Set the realname.
	 * @param realname The realname to set
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/** 
	 * Returns the qq.
	 * @return String
	 */
	public String getQq() {
		return qq;
	}

	/** 
	 * Set the qq.
	 * @param qq The qq to set
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}
}