/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-09-2007
 * 
 * XDoclet definition:
 * @struts.form name="responselistForm"
 */
public class ResponselistForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** content property */
	private String content;

	/** topicid property */
	private String topicid;

	/** submittime property */
	private String submittime;

	/** name property */
	private String name;
	private String xq;
	private String title;
	private String author;

	/*
	 * Generated Methods
	 */

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getXq() {
		return xq;
	}

	public void setXq(String xq) {
		this.xq = xq;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContent() {
		return content;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/** 
	 * Returns the topicid.
	 * @return String
	 */
	public String getTopicid() {
		return topicid;
	}

	/** 
	 * Set the topicid.
	 * @param topicid The topicid to set
	 */
	public void setTopicid(String topicid) {
		this.topicid = topicid;
	}

	/** 
	 * Returns the submittime.
	 * @return String
	 */
	public String getSubmittime() {
		return submittime;
	}

	/** 
	 * Set the submittime.
	 * @param submittime The submittime to set
	 */
	public void setSubmittime(String submittime) {
		this.submittime = submittime;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
}