/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-12-2007
 * 
 * XDoclet definition:
 * @struts.form name="userManagerForm"
 */
public class UserManagerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** tx property */
	private String tx;

	/** username property */
	private String username;

	/** grade property */
	private String grade;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the tx.
	 * @return String
	 */
	public String getTx() {
		return tx;
	}

	/** 
	 * Set the tx.
	 * @param tx The tx to set
	 */
	public void setTx(String tx) {
		this.tx = tx;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the grade.
	 * @return String
	 */
	public String getGrade() {
		return grade;
	}

	/** 
	 * Set the grade.
	 * @param grade The grade to set
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}
}