/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.wsy.struts.bean.ForumBean;
import com.wsy.struts.form.ForumAddForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-16-2007
 * 
 * XDoclet definition:
 * @struts.action path="/forumAdd" name="forumAddForm" input="/forumadd.jsp" scope="request" validate="true"
 */
public class ForumAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ForumAddForm forumAddForm = (ForumAddForm) form;// TODO Auto-generated method stub
		ActionMessages message=new ActionMessages();
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		String forumname=forumAddForm.getForumname();
		ForumBean forum=new ForumBean();
		int i=forum.UpdateRecord(forumname, datasource);//增加论坛方法
		if(i==1){
			message.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage("success.edit"));
			saveErrors(request,message);
			request.setAttribute("sucess", "ok");
		}
		return mapping.getInputForward();
	}
}