/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.wsy.struts.bean.ForumBean;
import com.wsy.struts.bean.LoginBean;
import com.wsy.struts.form.LoginForm;
import com.wsy.struts.util.StringTrans;

/** 
 * MyEclipse Struts
 * Creation date: 11-03-2007
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Log log=LogFactory.getLog("logtest");
		log.trace("trace");
		log.debug("debug");
		log.info("info");
		log.warn("warn");
		log.error("error");
		log.fatal("fatal");
		
		StringTrans s=new StringTrans();
		ActionMessages error=new ActionMessages();
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		HttpSession session=request.getSession();
		String name=loginForm.getName();//取文本框中的值
		String password=loginForm.getPassword();
		String grade="user";//定义取用户级别的变量,默认为user
		System.out.println("LoginAction"+s.tranC(name));


		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		LoginBean l=new LoginBean();
		ForumBean f=new ForumBean();
		int i=l.login(name, password, datasource);//变量i返回用户名密码是否正确
		List listuser=l.getRecordForUser(name, datasource);//取出此用户名的相关信息
		if(listuser!=null){
			for(int j=0;j<listuser.size();j++){
				LoginBean login=(LoginBean)listuser.get(j);
				grade=login.getGrade();//取出此用户的级别
			}
		}

		List list=f.getRecord(datasource);//取出论坛信息表中全部内容
		int ztcount=f.getCount(datasource);//取出主题总数
		int ztAndResponseCount=f.getZtAndResponseCount(datasource);//取总共帖子数
		int todaycount=f.getTodayResponseCount(datasource);
		session.setAttribute("list", list);
		session.setAttribute("ztcount", ztcount+"");
		session.setAttribute("ztAndResponseCount", ztAndResponseCount+"");
		session.setAttribute("todaycount", todaycount+"");
		session.setAttribute("i", i+"");//返回验证是否登录变量i
		System.out.println("usergrade"+grade);
		if(i==1&&(grade.equals("user")||grade.equals("bz"))){//如果验证成功并且用户级别是user或则bz时，转入index.jsp
			
			session.setAttribute("name",s.tranC(name));
			return mapping.findForward("success");
		}
		else if(i==0){//如果验证失败将错误信息返回index.jsp页面
			error.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage("error.login.failed"));
			saveErrors(request,error);
		}
		else if(i==1&&grade.equals("admin")){//如果验证成功并且用户级别是admin，转入adminindex.jsp页面
			System.out.println("test");
			ForumBean forum=new ForumBean();
			LoginBean login=new LoginBean();
			List listforum=forum.getRecord(datasource);//取论坛相关信息
			List listusertotal=login.getTotalRecord(datasource);//取用户相关信息
			session.setAttribute("listusertotal", listusertotal);
			session.setAttribute("listforum", listforum);
			return mapping.findForward("adminsuccess");
		}
		return mapping.getInputForward();
	}
}