/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import com.wsy.struts.bean.LoginBean;
import com.wsy.struts.bean.ResponseBean;
import com.wsy.struts.bean.TopicListBean;
import com.wsy.struts.form.ResponselistForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-09-2007
 * 
 * XDoclet definition:
 * @struts.action path="/responselist" name="responselistForm" input="/responselist.jsp" scope="request" validate="true"
 */
public class ResponselistAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ResponselistForm responselistForm = (ResponselistForm) form;// TODO Auto-generated method stub
		ActionMessages error=new ActionMessages();
		HttpSession session=request.getSession();
		String topicid=request.getParameter("topicid");
		System.out.println(topicid);
		String name=request.getParameter("name");//登录人
		
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		TopicListBean t=new TopicListBean();
		List listTopic=t.getTotalRecordTopic(topicid, datasource);//取这个主题的相关回复信息
		List listResponse=t.getRecordResponse(topicid, datasource);
		/*String content=request.getParameter("content");//主题内容
		String submittime=request.getParameter("submittime");//主题创建时间
		String topicid=request.getParameter("topicid");//主题id
		String xq=request.getParameter("xq");//主题中作者心情
		String title=request.getParameter("title");//主题题目
		String author=request.getParameter("zuozhe");//主题作者
		
		

		
		System.out.println("responseActiontauthor"+author);
	*/	
		String author=null;
		String content=null;
		String xq=null;
		String title=null;
		String submittime=null;
		
		
		for(int i=0;i<listTopic.size();i++){
			TopicListBean topic=(TopicListBean)listTopic.get(i);
			author=topic.getAuthor();
			System.out.println("author"+author);
			content=topic.getContent();
			xq=topic.getXq();
			title=topic.getTitle();
			submittime=topic.getSubmittime();
		}
		session.setAttribute("content", content);
		session.setAttribute("submittime", submittime);
		session.setAttribute("xq", xq);
		session.setAttribute("title", title);
		session.setAttribute("topicname", title);
		session.setAttribute("topicid", topicid);
		session.setAttribute("author", author);
		session.setAttribute("name", name);
		
		
		session.setAttribute("DataSource", datasource);
		int w=t.UpdateRq(topicid, datasource);//增加主题人气变量
		
		
		LoginBean l=new LoginBean();
		List list=l.getRecordForUser(name, datasource);//取出登录用户的相关信息
		List listauthor=l.getRecordForUser(author, datasource);//取出主题作者（发起人）的相关信息
		String responseAuthor=null;
		
		
		session.setAttribute("listResponse", listResponse);//回复内容做成Session
		session.setAttribute("listresponseuser", list);//登录用户的相关信息做成session
		session.setAttribute("listauthor", listauthor);//发起人的相关信息。
		//session.setAttribute("listResponseauthor", listResponseauthor);//回复作者相关信息
		return mapping.getInputForward();
	}
}