/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wsy.struts.bean.TopicListBean;
import com.wsy.struts.form.TopicmanagerForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-16-2007
 * 
 * XDoclet definition:
 * @struts.action path="/topicmanager" name="topicmanagerForm" input="/topicmanager.jsp" scope="request" validate="true"
 */
public class TopicmanagerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TopicmanagerForm topicmanagerForm = (TopicmanagerForm) form;// TODO Auto-generated method stub
		TopicListBean topic=new TopicListBean();
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		List listtotalTopic=topic.getTotalRecordTopic(datasource);
		HttpSession session=request.getSession();
		session.setAttribute("listtotalTopic", listtotalTopic);
		return mapping.getInputForward();
	}
}