/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wsy.struts.bean.ForumBean;
import com.wsy.struts.bean.LoginBean;
import com.wsy.struts.form.UeditForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-14-2007
 * 
 * XDoclet definition:
 * @struts.action path="/uedit" name="ueditForm" input="/usermanager.jsp" scope="request" validate="true"
 */
public class UeditAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UeditForm ueditForm = (UeditForm) form;// TODO Auto-generated method stub
		HttpSession session=request.getSession();
		String name=ueditForm.getName();
		String bz=ueditForm.getBz();
		String grade=ueditForm.getGrade();
		String id=ueditForm.getId();
		String ifbz=ueditForm.getIfbz();
		System.out.println(ifbz.equals("y"));
		LoginBean login=new LoginBean();
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		int i=login.UpdateRecord(id, name, grade, datasource);//修改tb_user表中用户的权限
		int j=0;
		if(ifbz.equals("y")||grade.equals("bz")){//如果单击了下拉菜单中的“斑竹”,设置隐含文本框的值为"y",如果为"y",更新tb_forum表中的斑竹,或则一开始就是斑竹，也需要更新tb_forum表。
			ForumBean f=new ForumBean();
			j=f.UpdateRecord(bz, name, datasource);
		}
		//System.out.println("i"+i);
		//System.out.println("j"+j);
		session.setAttribute("i", i+"");
		session.setAttribute("j", j+"");
		
		return mapping.getInputForward();
	}
}