/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wsy.struts.bean.ForumBean;
import com.wsy.struts.form.UsereditForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-12-2007
 * 
 * XDoclet definition:
 * @struts.action path="/useredit" name="usereditForm" input="/useredit.jsp" scope="request" validate="true"
 */
public class UsereditAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsereditForm usereditForm = (UsereditForm) form;// TODO Auto-generated method stub
		HttpSession session=request.getSession();
		String id=usereditForm.getId();
		String name=usereditForm.getName();
		String grade=(String)session.getAttribute("grade");
		
		ForumBean f=new ForumBean();
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		List listforum=f.getRecord(datasource);
		session.setAttribute("listforum", listforum);
		return mapping.getInputForward();
	}
}