/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wsy.struts.form.UserdeleteForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-15-2007
 * 
 * XDoclet definition:
 * @struts.action path="/userdelete" name="userdeleteForm" input="/userdelete.jsp" scope="request" validate="true"
 */
public class UserdeleteAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserdeleteForm userdeleteForm = (UserdeleteForm) form;// TODO Auto-generated method stub
		return null;
	}
}