/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.wsy.struts.bean.LoginBean;
import com.wsy.struts.bean.TopicListBean;
import com.wsy.struts.util.StringTrans;

/** 
 * MyEclipse Struts
 * Creation date: 11-15-2007
 * 
 * XDoclet definition:
 * @struts.action path="/userDel" name="userDelForm" input="/userdelete.jsp" scope="request" validate="true"
 */
public class UserDelAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StringTrans s=new StringTrans();
		HttpSession session=request.getSession();
		ActionMessages message=new ActionMessages();
		String id=(String)session.getAttribute("id");
		String name=(String)session.getAttribute("user");
		System.out.println("UserDelAction"+s.tranC(s.tranC(name)));
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		LoginBean login=new LoginBean();
		TopicListBean t=new TopicListBean();
		int i=login.deleteRecord(id, datasource);//删除用户
		int j=t.delRecordforUser(name, datasource);
		System.out.println(j);
		if(i==1){
			message.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage("success.del"));
			saveErrors(request,message);
			request.setAttribute("sucess", "ok");
		}
		return mapping.getInputForward();
	}
}