/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wsy.struts.bean.LoginBean;
import com.wsy.struts.form.UsersearchForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-12-2007
 * 
 * XDoclet definition:
 * @struts.action path="/usersearch" name="usersearchForm" input="/usersearch.jsp" scope="request" validate="true"
 */
public class UsersearchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsersearchForm usersearchForm = (UsersearchForm) form;// TODO Auto-generated method stub
		String name=usersearchForm.getName();
		LoginBean login=new LoginBean();
		HttpSession session=request.getSession();
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		List listsearchname=login.getRecordForUser(name, datasource);
		session.setAttribute("listsearchname", listsearchname);
		return mapping.getInputForward();
	}
}