/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wsy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.wsy.struts.bean.LoginBean;
import com.wsy.struts.form.UserManagerForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-12-2007
 * 
 * XDoclet definition:
 * @struts.action path="/userManager" name="userManagerForm" input="/userManager.jsp" scope="request" validate="true"
 */
public class UserManagerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserManagerForm userManagerForm = (UserManagerForm) form;// TODO Auto-generated method stub
		ActionMessages error=new ActionMessages();
		DataSource datasource = getDataSource(request,"dataSources");//取struts配置的数据源
		HttpSession session=request.getSession();
		LoginBean l=new LoginBean();
		List list=l.getTotalRecord(datasource);
		if(list!=null){
			session.setAttribute("listuser", list);
		}
		else{
			error.add(ActionMessages.GLOBAL_MESSAGE,new ActionMessage("error.usertable.null"));
			saveErrors(request,error);
		}
		return mapping.getInputForward();
	}
}