package com.mwq.hibernate.mapping;

import java.util.HashSet;
import java.util.Set;


/**
 * TbAccountItem generated by MyEclipse - Hibernate Tools
 */

public class TbAccountItem  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String type;
     private String unit;
     private String isTimecard;
     private Set tbTimecards = new HashSet(0);
     private Set tbReckoningInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbAccountItem() {
    }

	/** minimal constructor */
    public TbAccountItem(Integer id, String name, String type, String unit, String isTimecard) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.unit = unit;
        this.isTimecard = isTimecard;
    }
    
    /** full constructor */
    public TbAccountItem(Integer id, String name, String type, String unit, String isTimecard, Set tbTimecards, Set tbReckoningInfos) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.unit = unit;
        this.isTimecard = isTimecard;
        this.tbTimecards = tbTimecards;
        this.tbReckoningInfos = tbReckoningInfos;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getIsTimecard() {
        return this.isTimecard;
    }
    
    public void setIsTimecard(String isTimecard) {
        this.isTimecard = isTimecard;
    }

    public Set getTbTimecards() {
        return this.tbTimecards;
    }
    
    public void setTbTimecards(Set tbTimecards) {
        this.tbTimecards = tbTimecards;
    }

    public Set getTbReckoningInfos() {
        return this.tbReckoningInfos;
    }
    
    public void setTbReckoningInfos(Set tbReckoningInfos) {
        this.tbReckoningInfos = tbReckoningInfos;
    }
   








}