package com.mwq.hibernate.mapping;

import java.util.HashSet;
import java.util.Set;


/**
 * TbAccessionForm generated by MyEclipse - Hibernate Tools
 */

public class TbAccessionForm  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private Set tbDutyInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbAccessionForm() {
    }

	/** minimal constructor */
    public TbAccessionForm(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
    
    /** full constructor */
    public TbAccessionForm(Integer id, String name, Set tbDutyInfos) {
        this.id = id;
        this.name = name;
        this.tbDutyInfos = tbDutyInfos;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getTbDutyInfos() {
        return this.tbDutyInfos;
    }
    
    public void setTbDutyInfos(Set tbDutyInfos) {
        this.tbDutyInfos = tbDutyInfos;
    }
   








}