 package com.mwq.hibernate.mapping;

import java.util.Date;

/**
 * TbDutyInfo generated by MyEclipse - Hibernate Tools
 */

public class TbDutyInfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private TbDept tbDept;

	private TbDuty tbDuty;

	private TbAccessionForm tbAccessionForm;

	private Date accessionDate;

	private Date dimissionDate;

	private String dimissionReason;

	private Date firstPactDate;

	private Date pactStartDate;

	private Date pactEndDate;

	private String bankName;

	private String bankNo;

	private String societySafetyNo;

	private String annuitySafetyNo;

	private String doleSafetyNo;

	private String medicareSafetyNo;

	private String compoSafetyNo;

	private String accumulationFundNo;

	private TbRecord tbRecord;

	// Constructors

	public TbDutyInfo() {
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TbDept getTbDept() {
		return this.tbDept;
	}

	public void setTbDept(TbDept tbDept) {
		this.tbDept = tbDept;
	}

	public TbDuty getTbDuty() {
		return this.tbDuty;
	}

	public void setTbDuty(TbDuty tbDuty) {
		this.tbDuty = tbDuty;
	}

	public TbAccessionForm getTbAccessionForm() {
		return this.tbAccessionForm;
	}

	public void setTbAccessionForm(TbAccessionForm tbAccessionForm) {
		this.tbAccessionForm = tbAccessionForm;
	}

	public Date getAccessionDate() {
		return this.accessionDate;
	}

	public void setAccessionDate(Date accessionDate) {
		this.accessionDate = accessionDate;
	}

	public Date getDimissionDate() {
		return this.dimissionDate;
	}

	public void setDimissionDate(Date dimissionDate) {
		this.dimissionDate = dimissionDate;
	}

	public String getDimissionReason() {
		return this.dimissionReason;
	}

	public void setDimissionReason(String dimissionReason) {
		this.dimissionReason = dimissionReason;
	}

	public Date getFirstPactDate() {
		return this.firstPactDate;
	}

	public void setFirstPactDate(Date firstPactDate) {
		this.firstPactDate = firstPactDate;
	}

	public Date getPactStartDate() {
		return this.pactStartDate;
	}

	public void setPactStartDate(Date pactStartDate) {
		this.pactStartDate = pactStartDate;
	}

	public Date getPactEndDate() {
		return this.pactEndDate;
	}

	public void setPactEndDate(Date pactEndDate) {
		this.pactEndDate = pactEndDate;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	public String getSocietySafetyNo() {
		return this.societySafetyNo;
	}

	public void setSocietySafetyNo(String societySafetyNo) {
		this.societySafetyNo = societySafetyNo;
	}

	public String getAnnuitySafetyNo() {
		return this.annuitySafetyNo;
	}

	public void setAnnuitySafetyNo(String annuitySafetyNo) {
		this.annuitySafetyNo = annuitySafetyNo;
	}

	public String getDoleSafetyNo() {
		return this.doleSafetyNo;
	}

	public void setDoleSafetyNo(String doleSafetyNo) {
		this.doleSafetyNo = doleSafetyNo;
	}

	public String getMedicareSafetyNo() {
		return this.medicareSafetyNo;
	}

	public void setMedicareSafetyNo(String medicareSafetyNo) {
		this.medicareSafetyNo = medicareSafetyNo;
	}

	public String getCompoSafetyNo() {
		return this.compoSafetyNo;
	}

	public void setCompoSafetyNo(String compoSafetyNo) {
		this.compoSafetyNo = compoSafetyNo;
	}

	public String getAccumulationFundNo() {
		return this.accumulationFundNo;
	}

	public void setAccumulationFundNo(String accumulationFundNo) {
		this.accumulationFundNo = accumulationFundNo;
	}

	public TbRecord getTbRecord() {
		return tbRecord;
	}

	public void setTbRecord(TbRecord tbRecord) {
		this.tbRecord = tbRecord;
	}

}