package com.mwq.hibernate.mapping;

import java.util.HashSet;
import java.util.Set;


/**
 * TbDuty generated by MyEclipse - Hibernate Tools
 */

public class TbDuty  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private Set tbDutyInfos = new HashSet(0);
     private Set tbRedeploiesForQuondamDutyId = new HashSet(0);
     private Set tbRedeploiesForNowadayDutyId = new HashSet(0);


    // Constructors

    /** default constructor */
    public TbDuty() {
    }

	/** minimal constructor */
    public TbDuty(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
    
    /** full constructor */
    public TbDuty(Integer id, String name, Set tbDutyInfos, Set tbRedeploiesForQuondamDutyId, Set tbRedeploiesForNowadayDutyId) {
        this.id = id;
        this.name = name;
        this.tbDutyInfos = tbDutyInfos;
        this.tbRedeploiesForQuondamDutyId = tbRedeploiesForQuondamDutyId;
        this.tbRedeploiesForNowadayDutyId = tbRedeploiesForNowadayDutyId;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getTbDutyInfos() {
        return this.tbDutyInfos;
    }
    
    public void setTbDutyInfos(Set tbDutyInfos) {
        this.tbDutyInfos = tbDutyInfos;
    }

    public Set getTbRedeploiesForQuondamDutyId() {
        return this.tbRedeploiesForQuondamDutyId;
    }
    
    public void setTbRedeploiesForQuondamDutyId(Set tbRedeploiesForQuondamDutyId) {
        this.tbRedeploiesForQuondamDutyId = tbRedeploiesForQuondamDutyId;
    }

    public Set getTbRedeploiesForNowadayDutyId() {
        return this.tbRedeploiesForNowadayDutyId;
    }
    
    public void setTbRedeploiesForNowadayDutyId(Set tbRedeploiesForNowadayDutyId) {
        this.tbRedeploiesForNowadayDutyId = tbRedeploiesForNowadayDutyId;
    }
   








}